import { z } from 'zod';

/**
 * Control character regex (reject ASCII control chars 0x00-0x1F and 0x7F-0x9F except newlines/tabs if desired).
 */
const CONTROL_CHARS_REGEX = /[\u0000-\u0008\u000B\u000C\u000E-\u001F\u007F-\u009F]/;

/**
 * Zod schema for chat message sending.
 */
export const sendMessagePayloadSchema = z.object({
  /** Unique message identifier generated by client (nanoid) */
  messageId: z
    .string()
    .min(1, 'messageId must not be empty')
    .max(50, 'messageId exceeds maximum length'),

  /** Target room ID */
  roomId: z
    .string()
    .min(1, 'roomId must not be empty')
    .max(50, 'roomId exceeds maximum length'),

  /** Message text content */
  message: z
    .string()
    .transform((str) => str.trim())
    .pipe(
      z
        .string()
        .min(1, 'Chat message must not be empty')
        .max(1000, 'Chat message exceeds 1000 character limit')
        .refine((val) => !CONTROL_CHARS_REGEX.test(val), {
          message: 'Chat message contains invalid control characters',
        }),
    ),

  /** Optional client-supplied displayName — server overrides with verified room displayName */
  displayName: z.string().max(50).optional(),
});

export type SendMessagePayload = z.infer<typeof sendMessagePayloadSchema>;
